root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login
        permanent: false

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# error-prevention
homepage:
    pattern: /
    defaults:
            path: /login

application_subscriber:
    resource: "@ApplicationSubscriberBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

student_help:
    path: /help
    defaults: { _controller: SonataUserBundle:Help:index }

student_check:
    path: /check
    defaults: { _controller: SonataUserBundle:StudentCheck:index }

student_choose:
    path: /choose
    defaults: { _controller: SonataUserBundle:StudentCheck:choose }

modules:
    path: /modules
    defaults: { _controller: SonataUserBundle:Modules:index }